---
apiVersion: v1
kind: Template
metadata:
  name: floorist-operator
objects:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: floorplans.metrics.console.redhat.com
  spec:
    group: metrics.console.redhat.com
    names:
      kind: FloorPlan
      listKind: FloorPlanList
      plural: floorplans
      singular: floorplan
    scope: Namespaced
    versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: FloorPlan is the Schema for the floorplans API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource
                this object represents. Servers may infer this from the endpoint the
                client submits requests to. Cannot be updated. In CamelCase. More
                info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of FloorPlan
              properties:
                database:
                  description: The database specification ClowdApp specification.
                  properties:
                    secretName:
                      description: Secret containing a database credentials.
                      type: string
                  required:
                  - secretName
                  type: object
                logLevel:
                  default: INFO
                  description: Sets logging level of floorist execution. See https://docs.python.org/3/library/logging.html?highlight=logging#logging-levels
                    for expected values.
                  type: string
                objectStore:
                  description: Object Storage (S3) configuration.
                  properties:
                    secretName:
                      description: Name of the object store secret containing credentials.
                      type: string
                  required:
                  - secretName
                  type: object
                queries:
                  description: List of Floorist queries to export as prefix-query
                    pairs.
                  items:
                    description: Floorist Query definition.
                    properties:
                      chunksize:
                        description:
                        type: integer
                      prefix:
                        description: Valid folder path that will be created under
                          the bucket.
                        type: string
                      query:
                        description: A sinqle SQL query to export as metric.
                        type: string
                    required:
                    - prefix
                    - query
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  type: array
                resources:
                  description: A resource requirements in k8s ResourceRequirements
                    format. If omitted, the default resources would be applied. Default
                    requests CPU 50m, memory 250Mi and limits CPU 100m, memory 500Mi.
                  properties:
                    limits:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                        x-kubernetes-int-or-string: true
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                      type: object
                    requests:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                        x-kubernetes-int-or-string: true
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                      type: object
                  type: object
                suspend:
                  default: false
                  description: This flag tells the controller to suspend subsequent
                    executions, it does not apply to already started executions.  Defaults
                    to false. Only applies to Cronjobs
                  type: boolean
              required:
              - database
              - objectStore
              - queries
              type: object
            status:
              description: Status defines the observed state of FloorPlan.
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: floorist-operator-controller-manager
    namespace: floorist-operator-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: floorist-operator-leader-election-role
    namespace: floorist-operator-system
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ''
    resources:
    - events
    verbs:
    - create
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      managed.openshift.io/aggregate-to-dedicated-admins: cluster
      rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    name: floorist-operator-floorplan-editor-role
  rules:
  - apiGroups:
    - metrics.console.redhat.com
    resources:
    - floorplans
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - metrics.console.redhat.com
    resources:
    - floorplans/status
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      rbac.authorization.k8s.io/aggregate-to-view: 'true'
    name: floorist-operator-floorplan-viewer-role
  rules:
  - apiGroups:
    - metrics.console.redhat.com
    resources:
    - floorplans
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - metrics.console.redhat.com
    resources:
    - floorplans/status
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: floorist-operator-manager-role
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - batch
    resources:
    - cronjobs
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - metrics.console.redhat.com
    resources:
    - floorplans
    - floorplans/status
    - floorplans/finalizers
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: floorist-operator-leader-election-rolebinding
    namespace: floorist-operator-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: floorist-operator-leader-election-role
  subjects:
  - kind: ServiceAccount
    name: floorist-operator-controller-manager
    namespace: floorist-operator-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: floorist-operator-manager-rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: floorist-operator-manager-role
  subjects:
  - kind: ServiceAccount
    name: floorist-operator-controller-manager
    namespace: floorist-operator-system
- apiVersion: v1
  data:
    controller_manager_config.yaml: |
      apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
      kind: ControllerManagerConfig
      health:
        healthProbeBindAddress: :6789
      metrics:
        bindAddress: 127.0.0.1:8080

      leaderElection:
        leaderElect: true
        resourceName: 811c9dc5.console.redhat.com
  kind: ConfigMap
  metadata:
    name: floorist-operator-manager-config
    namespace: floorist-operator-system
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: floorist-manager
    name: floorist-operator-manager-metrics
    namespace: floorist-operator-system
  spec:
    ports:
    - name: metrics
      port: 9000
      protocol: TCP
      targetPort: 8080
    selector:
      control-plane: controller-manager
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: minimum three replicas not
        required
    labels:
      control-plane: controller-manager
    name: floorist-operator-controller-manager
    namespace: floorist-operator-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        control-plane: controller-manager
    template:
      metadata:
        annotations:
          ignore-check.kube-linter.io/minimum-three-replicas: minimum three replicas
            not required
          kubectl.kubernetes.io/default-container: manager
        labels:
          control-plane: controller-manager
      spec:
        containers:
        - args:
          - "--leader-elect"
          - "--leader-election-id=floorist-operator"
          - "--max-concurrent-reconciles=1"
          env:
          - name: ANSIBLE_GATHERING
            value: explicit
          - name: FLOORIST_IMAGE
            value: "${FLOORIST_IMAGE}"
          - name: FLOORIST_IMAGE_TAG
            value: "${FLOORIST_IMAGE_TAG}"
          image: "${IMAGE}:${IMAGE_TAG}"
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          readinessProbe:
            httpGet:
              path: "/readyz"
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 10m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
        securityContext:
          runAsNonRoot: true
        serviceAccountName: floorist-operator-controller-manager
        terminationGracePeriodSeconds: 10
parameters:
- description: Operator image
  name: IMAGE
  value: quay.io/cloudservices/floorist-operator
- description: Operator image tag
  name: IMAGE_TAG
  value: latest
- description: Floorist exporter tool image
  name: FLOORIST_IMAGE
  value: quay.io/cloudservices/floorist
- description: Floorist exporter tool image tag
  name: FLOORIST_IMAGE_TAG
  value: 109e5ec
