---
apiVersion: v1
kind: Template
metadata:
  name: floorist-operator-stage-test
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: floorist-operator-stage-test-service-account
    namespace: floorist-operator-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: floorist-operator-stage-test-role
    namespace: floorist-operator-system
  rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: floorist-operator-stage-test-rolebinding
    namespace: floorist-operator-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: floorist-operator-stage-test-role
  subjects:
  - kind: ServiceAccount
    name: floorist-operator-stage-test-service-account
    namespace: floorist-operator-system
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: floorist-operator-stage-test-${IMAGE_TAG}
    namespace: floorist-operator-system
  spec:
    backoffLimit: 2
    template:
      spec:
        containers:
        - args:
          - stage_test.sh
          command:
          - sh
          image: "${IMAGE}:${IMAGE_TAG}"
          imagePullPolicy: Always
          name: floorist-operator-stage-test
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        restartPolicy: Never
        serviceAccountName: floorist-operator-stage-test-service-account
parameters:
- description: Operator image
  name: IMAGE
  value: quay.io/redhat-services-prod/insights-management-tenant/insights-floorist/floorist-operator
- description: Operator image tag
  name: IMAGE_TAG
  value: ''
  required: true
