---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
  annotations:
    ignore-check.kube-linter.io/minimum-three-replicas: "minimum three replicas not required"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        ignore-check.kube-linter.io/minimum-three-replicas: "minimum three replicas not required"
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - --leader-elect
        - --leader-election-id=floorist-operator
        - "--max-concurrent-reconciles=1"
        image: controller:latest
        name: manager
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: FLOORIST_IMAGE
          value: quay.io/redhat-services-prod/insights-management-tenant/insights-floorist/floorist
        - name: FLOORIST_IMAGE_TAG
          value: latest
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
          protocol: TCP
          name: metrics
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6789
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 10m
            memory: 256Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
