resources:
- ./local

images:
- name: quay.io/redhat-services-prod/insights-management-tenant/insights-floorist/floorist-operator
  newName: ${IMAGE}
  newTag: ${IMAGE_TAG}

patches:
- path: test_params.config.yaml
  target:
    group: batch
    kind: Job
    name: stage-test
    version: v1

patchesStrategicMerge:
- clusterrole_patch.yaml
