apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: floorist-operator-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: floorist-operator-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

resources:
- cronjob_viewer_clusterrole.yaml
- cronjob_viewer_role_binding.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- stage_test.yaml

images:
- name: controller
  newName: quay.io/redhat-services-prod/insights-management-tenant/insights-floorist/floorist-operator
  newTag: latest
